<?
$aMenuLinks = array(
    array(
        "О магазине",
        "/about/",
        array(),
        array(),
        ""
    ),
    array(
        "Новости",
        "/news/",
        array(),
        array(),
        ""
    ),
    /*array(
        "Блог",
        "/blog/",
        array(),
        array(),
        ""
    ),*/
    /*array(
        "Сотрудничество",
        "/cooperation/",
        array(),
        array(),
        ""
    ),*/
    array(
        "Контакты",
        "/contacts/",
        array(),
        array(),
        ""
    ),
);
