<div class="section-blog container">
  <div class="section-header">
    <div class="title title--medium">
      Блог
    </div>
  </div>

  <?
  $APPLICATION->IncludeComponent(
    "bitrix:news",
    "blog",
    array(
      "DISPLAY_DATE" => "Y",
      "DISPLAY_PICTURE" => "Y",
      "DISPLAY_PREVIEW_TEXT" => "Y",
      "SEF_MODE" => "Y",
      "AJAX_MODE" => "N",
      "IBLOCK_ID" => BLOG_ID,
      "IBLOCK_TYPE" => "blog",
      "NEWS_COUNT" => "3",
      "USE_SEARCH" => "N",
      "USE_RSS" => "N",
      "USE_RATING" => "N",
      "USE_CATEGORIES" => "N",
      "USE_REVIEW" => "N",
      "USE_FILTER" => "N",
      "SORT_BY1" => "ACTIVE_FROM",
      "SORT_ORDER1" => "DESC",
      "SORT_BY2" => "SORT",
      "SORT_ORDER2" => "ASC",
      "CHECK_DATES" => "Y",
      "PREVIEW_TRUNCATE_LEN" => "",
      "LIST_ACTIVE_DATE_FORMAT" => "d.m.Y",
      "LIST_FIELD_CODE" => array(
        0 => "",
        1 => "",
      ),
      "LIST_PROPERTY_CODE" => array(
        0 => "",
        1 => "",
      ),
      "HIDE_LINK_WHEN_NO_DETAIL" => "Y",
      "DISPLAY_NAME" => "Y",
      "META_KEYWORDS" => "-",
      "META_DESCRIPTION" => "-",
      "BROWSER_TITLE" => "-",
      "DETAIL_SET_CANONICAL_URL" => "Y",
      "DETAIL_ACTIVE_DATE_FORMAT" => "d.m.Y",
      "DETAIL_FIELD_CODE" => array(
        0 => "DATE_CREATE",
        1 => "",
      ),
      "DETAIL_PROPERTY_CODE" => array(
        0 => "",
        1 => "",
      ),
      "DETAIL_DISPLAY_TOP_PAGER" => "Y",
      "DETAIL_DISPLAY_BOTTOM_PAGER" => "Y",
      "DETAIL_PAGER_TITLE" => "Страница",
      "DETAIL_PAGER_TEMPLATE" => "",
      "DETAIL_PAGER_SHOW_ALL" => "Y",
      "STRICT_SECTION_CHECK" => "Y",
      "SET_TITLE" => "N",
      "ADD_SECTIONS_CHAIN" => "Y",
      "ADD_ELEMENT_CHAIN" => "Y",
      "SET_LAST_MODIFIED" => "Y",
      "PAGER_BASE_LINK_ENABLE" => "Y",
      "SET_STATUS_404" => "Y",
      "SHOW_404" => "Y",
      "MESSAGE_404" => "",
      "PAGER_BASE_LINK" => "",
      "PAGER_PARAMS_NAME" => "arrPager",
      "INCLUDE_IBLOCK_INTO_CHAIN" => "N",
      "USE_PERMISSIONS" => "N",
      "GROUP_PERMISSIONS" => array(
        0 => "1",
      ),
      "CACHE_TYPE" => "A",
      "CACHE_TIME" => "3600",
      "CACHE_FILTER" => "Y",
      "CACHE_GROUPS" => "Y",
      "DISPLAY_TOP_PAGER" => "Y",
      "DISPLAY_BOTTOM_PAGER" => "Y",
      "PAGER_TITLE" => "Блог",
      "PAGER_SHOW_ALWAYS" => "Y",
      "PAGER_TEMPLATE" => "",
      "PAGER_DESC_NUMBERING" => "N",
      "PAGER_DESC_NUMBERING_CACHE_TIME" => "36000",
      "PAGER_SHOW_ALL" => "Y",
      "FILTER_NAME" => "",
      "FILTER_FIELD_CODE" => array(
        0 => "",
        1 => "",
      ),
      "FILTER_PROPERTY_CODE" => array(
        0 => "",
        1 => "",
      ),
      "NUM_NEWS" => "20",
      "NUM_DAYS" => "30",
      "YANDEX" => "Y",
      "MAX_VOTE" => "5",
      "VOTE_NAMES" => array(
        0 => "0",
        1 => "1",
        2 => "2",
        3 => "3",
        4 => "4",
        5 => "",
      ),
      "CATEGORY_IBLOCK" => "",
      "CATEGORY_CODE" => "CATEGORY",
      "CATEGORY_ITEMS_COUNT" => "5",
      "MESSAGES_PER_PAGE" => "10",
      "USE_CAPTCHA" => "Y",
      "REVIEW_AJAX_POST" => "Y",
      "PATH_TO_SMILE" => "/bitrix/images/forum/smile/",
      "FORUM_ID" => "",
      "URL_TEMPLATES_READ" => "",
      "SHOW_LINK_TO_FORUM" => "Y",
      "POST_FIRST_MESSAGE" => "Y",
      "SEF_FOLDER" => "/",
      "AJAX_OPTION_JUMP" => "N",
      "AJAX_OPTION_STYLE" => "Y",
      "AJAX_OPTION_HISTORY" => "N",
      "USE_SHARE" => "Y",
      "SHARE_HIDE" => "Y",
      "SHARE_TEMPLATE" => "",
      "SHARE_HANDLERS" => array(),
      "SHARE_SHORTEN_URL_LOGIN" => "",
      "SHARE_SHORTEN_URL_KEY" => "",
      "COMPONENT_TEMPLATE" => "blog",
      "AJAX_OPTION_ADDITIONAL" => "",
      "DISPLAY_AS_RATING" => "rating",
      "FILE_404" => "",
      "SEF_URL_TEMPLATES" => array(
        "news" => "",
        "section" => "#SECTION_CODE_PATH#/",
        "detail" => "#IBLOCK_CODE#/#SECTION_CODE_PATH#/#ELEMENT_CODE#/",
      )
    ),
    false
  );
  ?>
</div>
